macro (get_platform_qpa_plugin var)
  if (NOT QT_INSTALL_PLUGINS)
    query_qmake (QT_INSTALL_PLUGINS QT_INSTALL_PLUGINS)
  endif ()
  
  if (APPLE)
    set (${var} ${QT_INSTALL_PLUGINS}/platforms/libqcocoa.dylib)
  elseif (WIN32 AND MSVC)
    set (${var} ${QT_INSTALL_PLUGINS}/platforms/qwindows.dll)
  endif ()
endmacro ()

macro (get_target_location var target)
  if (NOT APPLE)
    cmake_policy (PUSH)
    cmake_policy (SET CMP0026 OLD)
    get_target_property (${var} ${target} LOCATION)
    cmake_policy (POP)
  else ()
    set (${var} ${target}.app)
  endif ()
endmacro ()
