set (CPACK_GENERATOR "DragNDrop")

include (CPackDefaultOptions)

if (APPLE AND CMAKE_INSTALL_PREFIX MATCHES "/usr/local")
    set (CMAKE_INSTALL_PREFIX "/Applications")
endif (APPLE AND CMAKE_INSTALL_PREFIX MATCHES "/usr/local")

string (REPLACE "_" "-" CPACK_PACKAGE_VERSION ${vatsinator_VERSION})

set (BIN_INSTALL_DIR ".")
set (DOC_INSTALL_DIR ".")

set (MACOSX_BUNDLE_INFO_STRING "${CMAKE_PROJECT_NAME} ${CPACK_PACKAGE_VERSION}")
set (MACOSX_BUNDLE_BUNDLE_VERSION "${CMAKE_PROJECT_NAME} ${CPACK_PACKAGE_VERSION}")
set (MACOSX_BUNDLE_LONG_VERSION_STRING "${CMAKE_PROJECT_NAME} ${CPACK_PACKAGE_VERSION}")
set (MACOSX_BUNDLE_SHORT_VERSION_STRING "${CPACK_PACKAGE_VERSION}")
set (MACOSX_BUNDLE_COPYRIGHT "2012 Vatsinator Team")
set (MACOSX_BUNDLE_ICON_FILE "${CMAKE_CURRENT_SOURCE_DIR}/source/ui/resources/vatsinator.icns")
set (MACOSX_BUNDLE_BUNDLE_NAME "${CMAKE_PROJECT_NAME}")
set (MACOSX_BUNDLE_RESOURCES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.app/Contents/Resources")
set (MACOSX_BUNDLE_ICON "${MACOSX_BUNDLE_ICON_FILE}")
execute_process (COMMAND ${CMAKE_COMMAND} -E make_directory ${MACOSX_BUNDLE_RESOURCES})
execute_process (COMMAND ${CMAKE_COMMAND} -E copy_if_different ${MACOSX_BUNDLE_ICON} ${MACOSX_BUNDLE_RESOURCES})

set (CPACK_DMG_FORMAT "UDBZ")
set (CPACK_DMG_VOLUME_NAME "${CMAKE_PROJECT_NAME}")
set (CPACK_SYSTEM_NAME "OSX")
set (CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}")
set (CPACK_BUNDLE_STARTUP_COMMAND "${CMAKE_CURRENT_BINARY_DIR}/vatsinator")

set (CPACK_PACKAGE_EXECUTABLES "vatsinator")

include (CPack)
