set (MACOSX_BUNDLE_ICON_FILE ${CMAKE_CURRENT_SOURCE_DIR}/source/ui/resources/vatsinator.icns)
set (MACOSX_BUNDLE_VERSION "${vatsinator_VERSION}")
set (MACOSX_BUNDLE_SHORT_VERSION_STRING "${vatsinator_VERSION}")
set (MACOSX_BUNDLE_LONG_VERSION_STRING "Version ${vatsinator_VERSION}")
set (MACOSX_BUNDLE_GUI_IDENTIFIER "Vatsinator")
set (MACOSX_BUNDLE_BUNDLE_NAME "Vatsinator")

