set (MACOSX_BUNDLE_ICON_FILE "${PROJECT_SOURCE_DIR}/dist/vatsinator.icns")
set (MACOSX_BUNDLE_VERSION "${vatsinator_VERSION}")
set (MACOSX_BUNDLE_SHORT_VERSION_STRING "${vatsinator_VERSION}")
set (MACOSX_BUNDLE_LONG_VERSION_STRING "Version ${vatsinator_VERSION}")
set (MACOSX_BUNDLE_GUI_IDENTIFIER "Vatsinator")
set (MACOSX_BUNDLE_BUNDLE_NAME "Vatsinator")

